### ISSUE TITLE
OrderItem does not correspond with documentation

### ISSUE THREAD

**Issue by zarubto4** [gopaycommunity/gopay-java-api#3]
OrderItem requred 4 values 

```
@XmlElement(name = "name")
private String name;

@XmlElement(name = "amount")
private Long amount;

@XmlElement(name = "fee")
private Long fee;

@XmlElement(name = "count")
private Long count;`
```

But documentation say that you have to used only two

`"items":[
              {"name":"item01","amount":"500"},
             {"name":"item02","amount":"500"}
            ],`

**Comment by FSichinger** [comment]
The fee property has no real functionallity, removed in 3.4.0
